service: ${env:AWS_SERVICE_NAME}

plugins:
  - serverless-content-encoding
  - serverless-webpack

custom:
  contentEncoding:
    minimumCompressionSize: 0
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    keepOutputDirectory: true
  true: true

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  deploymentBucket:
    name: ${env:AWS_SERVICE_NAME}
  region: ${env:AWS_REGION}
  stage: ${env:AWS_STAGE}

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          method: post
          path: graphql
          cors: true
          integration: lambda
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      DATABASE_SCHEMAS: ${env:DATABASE_SCHEMAS}
      SLS: ${self:custom.true}
